### ISSUE TITLE
[Python] Deal with a breaking change

### ISSUE THREAD

**Issue by puhitaku** [approvers/RADWIMPS#136]
The changes produced in PR #110 break existing behavior and public APIs. [Attributes with no leading underscores are considered public API.](https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables)

Related: #134 @shniubobo 

### Difference

Formerly ( ef67d36 ):
```
$ ipython
Python 3.8.2 (default, May 22 2020, 21:44:03)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import RADWIMPS

In [2]: RADWIMPS.RADWIMPS.then().then().then().世()
前前前世
Out[2]: RADWIMPS.RADWIMPS

In [3]:
Do you really want to exit ([y]/n)? y
$
```

And now ( 7cbc601 ):
```
$ ipython
Python 3.8.2 (default, May 22 2020, 21:44:03)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import RADWIMPS

In [2]: RADWIMPS.RADWIMPS.then().then().then().世()
Out[2]: 前前前<coroutine object RADWIMPS.世 at 0x106eb48c0>

In [3]:
Do you really want to exit ([y]/n)? y
/Users/takumi/.pyenv/versions/3.8.2/lib/python3.8/site-packages/IPython/core/interactiveshell.py:1445: RuntimeWarning: coroutine 'RADWIMPS.世' was never awaited
  self.user_ns_hidden.clear()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

 - No `print()` on invocation of `RADWIMPS.then()`
 - Returns a coroutine instead of `RADWIMPS.RADWIMPS`
 - Python scolds us on exit

This kind of change will confuse the users of the `RADWIMPS` module as it is not intended to return async stuff. While it is a joke repository, breaking changes should be carefully considered and avoided.

### Improvement

Async APIs are worth having. Forking `RADWIMPS.py` should solve this issue and rolls back to the code it ought to be. While async modules are named like `asyncfoobar.py` in general, it's better to name it `RADWIMPS_async.py` here.

```
$ cp RADWIMPS.py RADWIMPS_async.py  # queer capitalizing tho ;)
$ git revert 7cbc601
$ git add RADWIMPS_async.py
$ git commit -m "blahblah"
```

**Comment by shniubobo** [comment]
Thank you very much for pointing out the issue and providing its solution. I will make another pull request to fix the issue and suspend #134.
